package-lock.json, package.json, src/App.js, src/components/auth/UserLoginForm.js, src/index.js, src/pages/UserLoginPage.js
=> [Auth] 유저 로그인 페이지 추가

package-lock.json, package.json, src/lib/api/auth.js, src/lib/api/client.js
=> [Auth] axios인스턴스생성 & API 함수 작성

src/lib/api/boardInformaition.js
=> [Board/Information] API 함수 작성

src/lib/api/libraries.js
=> [Libraries]API 함수 작성

src/lib/api/boardNotice.js
=> boardNotice.js API 함수 작성

src/lib/api/boardMap.js
=> boardMap.js API 함수 작성

package-lock.json, package.json, src/App.js, src/components/auth/UserLoginForm.js, src/index.js, src/pages/HomePage.js, src/pages/UserLoginPage.js, src/styles/components/UserLoginForm.scss, src/styles/config/_reset.scss, src/styles/style.scss
npm install styled-components
npm install node-sass
npm install react-icons
=> [Auth] 로그인 폼 레이아웃 구성 & 통합 페이지 추가

package-lock.json, package.json, src/components/auth/UserLoginForm.js, src/components/auth/UserSignUpForm.js, src/container/auth/LoginForm.js, src/container/auth/SignUpForm.js, src/index.js, src/lib/api/auth.js, src/lib/createRequestSaga.js, src/modules/auth.js, src/modules/index.js, src/modules/loading.js, src/pages/UserLoginPage.js, src/pages/UserSignUpPage.js, src/styles/components/UserSignUpForm.scss, src/styles/style.scss
=> [Auth] 회원가입 폼 구현

src/App.js, src/components/libraries/LibrariesList.js, src/components/libraries/LibrariesListItem.js, src/pages/LibrariesListPage.js, src/styles/components/libraries/LibrariesList.scss, src/styles/components/libraries/LibrariesListItem.scss, src/styles/style.scss
=> [LibrariesList] 폼 구성 및 간단한 css착업

src/components/libraries/LibrariesList.js, src/components/libraries/LibrariesListItem.js, src/styles/components/libraries/LibrariesList.scss, src/styles/components/libraries/LibrariesListItem.scss
=> [LibrariesList] axios.get 오류 수정

src/lib/api/boardInformaition.js, src/lib/api/boardMap.js, src/lib/api/boardNotice.js, src/lib/api/client.js, src/lib/api/composite.js, src/lib/api/lending.js, src/lib/api/libraries.js
=> [client-users] lib/api 수정

package.json, src/App.js, src/components/auth/UserProfileForm.js, src/containers/auth/ProfileForm.js, src/modules/auth.js, src/pages/HomePage.js, src/pages/LoginSelectorPage.js, src/styles/components/UserPropfileForm.scss
프로필 페이지 기능 구현 보류
로그인 선택 페이지 추가
=> 프로필 페이지 보류 및 로그인 선택페이지 추가

src/App.js, src/components/board/BoardDetail.js, src/components/board/BoardDetailForm.js, src/components/board/BoardInfo.js, src/components/board/BoardList.js, src/components/board/BoardMap.js, src/components/board/BoardNoticeListItem.js, src/components/board/BoardSideBar.js, src/pages/board/BoardDetailPage.js, src/pages/board/BoardListPage.js, src/pages/board/GuidePage.js, src/pages/board/NoticesPage.js, src/styles/components/board/BoardDetail.scss, src/styles/components/board/BoardDetailForm.scss, src/styles/components/board/BoardInfo.scss, src/styles/components/board/BoardList.scss, src/styles/components/board/BoardListItem.scss, src/styles/components/board/BoardSideBar.scss, src/styles/style.scss
#87 
BoardDetail
BoardList
GuidePage.js
Notices.js 파일 이동
=> [Board] 개별도서관 게시판 페이지 추가

src/App.js, src/components/board/BoardList.js, src/components/board/BoardNoticeListItem.js, src/components/board/NoticesDetail.js, src/components/board/NoticesList.js, src/components/board/NoticesListItem.js, src/components/libraries/LibrariesList.js, src/components/libraries/LibrariesListItem.js, src/pages/HomePage.js, src/pages/LibraryMainPage.js, src/pages/board/NoticesDetailPage.js, src/pages/libraries/LibrariesListPage.js, src/styles/components/board/NoticeDetail.scss, src/styles/components/board/NoticesList.scss, src/styles/components/board/NoticesListItem.scss, src/styles/style.scss
#92 
도서관 개별 페이지 LibraryMainPage 추가
NoticesDetailPage 추가
API 연결 부분 주석 처리
=> [Board] route연결 및 도서관 개별 페이지 추가

src/components/UserMainForm.js, src/pages/HomePage.js, src/pages/home/Feature.js, src/pages/home/Navigations.js, src/pages/home/SearchBar.js, src/styles/home/feature.scss, src/styles/home/homepage.scss, src/styles/home/navigations.scss, src/styles/home/searchBar.scss, src/styles/style.scss
=> [Auth] 홈페이지 UI 작업

src/App.js, src/components/board/BoardList.js, src/components/board/BoardNoticeListItem.js, src/components/libraries/LibrariesDetail.js, src/components/libraries/LibraryMainForm.js, src/pages/libraries/LibrariesDetailPage.js, src/styles/components/libraries/LibrariesDetail.scss, src/styles/components/libraries/LibraryMainForm.scss, src/styles/style.scss
=> [libraries] 개별 도서관 페이지 및 상세정보 페이지

src/components/libraries/LibrariesListItem.js, src/styles/components/libraries/LibrariesDetail.scss, src/styles/components/libraries/LibrariesList.scss, src/styles/components/libraries/LibrariesListItem.scss, src/styles/components/libraries/LibraryMainForm.scss
=> [Libraries] css 수정

src/components/libraries/LibrariesDetail.js, src/styles/components/libraries/LibrariesDetail.scss
=> [libraries] icon 추가 및 css 수정

src/components/auth/UserLoginForm.js, src/pages/HomePage.js, src/styles/components/auth/UserLoginForm.scss, src/styles/components/auth/inputForm.scss, src/styles/home/header.scss, src/styles/style.scss
=> Feature/auth/fix login UI

src/components/auth/UserProfileForm.js, src/containers/auth/SignUpForm.js, src/lib/api/auth.js, src/pages/UserMainPage.js, src/pages/auth/FindIdPage.js, src/pages/auth/FindPwPage.js, src/pages/auth/UserLoginPage.js, src/pages/auth/UserProfilePage.js, src/pages/auth/UserSignUpPage.js
=> 프로필 정보 보여주기
